- id: '1542469377542'
  alias: Startup actions
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: sensor.update_speedtest
- id: '1544290360614'
  alias: Restart Netatmo Camera on connection loss
  trigger:
  - entity_id: binary_sensor.netatmo_welcome
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.w01
    service: switch.turn_off
  - delay: 00:00:03
  - data:
      entity_id: switch.w01
    service: switch.turn_on
