- id: '1607994327328'
  alias: Pause Spotify when my phone rings
  description: ''
  use_blueprint:
    path: ludeeus/pause_media_during_calls.yaml
    input:
      phone_state_sensor: sensor.sm_g973f_phone_state
      media_player:
        entity_id: media_player.spotify_joakim_sorensen
- id: '1630830932920'
  alias: Notify on remote UI disconnect
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.remote_ui
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Remote UI has disconnected
  mode: single
- id: '1630833470587'
  alias: Send notification when home assistant starts
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Home Assistant has started
  mode: single
- id: '1633555826324'
  alias: Turn on night lights
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: device
    device_id: d20d4fa889d9807b7d66ab290af4a9c1
    domain: device_tracker
    entity_id: device_tracker.iphone
    type: is_home
  action:
  - service: light.turn_on
    target:
      entity_id: light.led001
    data:
      color_name: homeassistant
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.w01
  mode: single
- id: '1633555882355'
  alias: Turn off night lights
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.chrome_cast
    to: playing
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      entity_id:
      - light.led001
      - switch.w01
  mode: single
- id: '1633761284031'
  alias: Good morning
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.spotify_joakim_sorensen
    to: Playing
  condition:
  - condition: time
    after: 06:00
    before: '12:00'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.w01
  - service: script.living_room_lights_default
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.w01
  mode: single
