#######################################################################################################################################
##  Default config
#######################################################################################################################################
homeassistant:
  name: Jarvis
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named Packages

#######################################################################################################################################
##  Include files
#######################################################################################################################################
binary_sensor: !include Include/binary_sensor.yaml
camera: !include Include/camera.yaml
device_tracker: !include Include/device_tracker.yaml
http: !include Include/http.yaml
ifttt: !include Include/ifttt.yaml
media_player: !include Include/media_player.yaml
mqtt: !include Include/mqtt.yaml
netatmo: !include Include/netatmo.yaml
notify: !include Include/notify.yaml
panel_iframe: !include Include/panel_iframe.yaml
shell_command: !include Include/shell.yaml
switch: !include Include/switch.yaml
tts: !include Include/tts.yaml

#######################################################################################################################################
##  Include folders
#######################################################################################################################################
automation: !include_dir_list Automation/
group: !include_dir_named Groups/
input_boolean: !include_dir_named Input/Boolean/
input_select: !include_dir_named Input/Select/
script: !include_dir_named Script/
sensor: !include_dir_list Sensor/

#######################################################################################################################################
##  Include functions
#######################################################################################################################################
#discovery:
frontend:
updater:
history:
  exclude:
    domains:
      - automation
logbook:
config:
recorder:
#  db_url: !secret db
  purge_days: 7
  exclude:
    domains:
      - sun
      - updater
    entities:
      - sun.sun
logger:
  default: warning
  logs:
    homeassistant.core: error
    #homeassistant.setup: critical
    #homeassistant.components.camera: critical
    #homeassistant.components.media_player: error
    #homeassistant.components.binary_sensor.template: error
    
google:
 client_id: !secret googleid
 client_secret: !secret googlesecret

#######################################################################################################################################
##  Zones
#######################################################################################################################################
zone:
  name: Home
  latitude: !secret z1la
  longitude: !secret z1lo
  radius: 30
  icon: mdi:home
zone 2:
  name: Skole
  latitude: !secret z2la
  longitude: !secret z2lo
  radius: 250
  icon: mdi:school
zone 3:
  name: Jobb
  latitude: !secret z3la
  longitude: !secret z3lo
  radius: 80
  icon: mdi:account-multiple
#######################################################################################################################################
# End of configuration file
#######################################################################################################################################
