############################################################################
##  Base `configuration.yaml` most stuff is in packages/*.yaml
############################################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  time_zone: Europe/Oslo
  packages: !include_dir_named packages
############################################################################
http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret base_url
############################################################################
discovery:
config:
updater:
conversation:
history:
logbook:
sun:
hassbian_config:
############################################################################
##  Hubs
############################################################################
netatmo:
  api_key: !secret netatmo_key
  secret_key: !secret netatmo_secret
  username: !secret gmail
  password: !secret netatmo_password
  discovery: false
#---------------------------------------------------------------------------
mqtt:
  broker: !secret mqtt-broker
  port: 1883
  username: !secret mqtt-user
  password: !secret mqtt-pass
############################################################################
