#######################################################################################################################################
##  Default config
#######################################################################################################################################
homeassistant:
  name: Jarvis
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_domain:
    script:
      icon: mdi:settings
    automation:
      icon: mdi:circle-outline
  customize_glob:
    'sensor.glances_*':
      icon: mdi:windows
      
#######################################################################################################################################
##  Include files
#######################################################################################################################################
device_tracker:
  - platform: icloud
    username: !secret ios-user
    password: !secret ios-password
  - platform: owntracks

ifttt:
  key: !secret ifttt-apikey
mqtt:
  broker: 192.168.1.2
  username: !secret mqtt-user
  password: !secret mqtt-password
tts:
  - platform: google
    language: 'no'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
#######################################################################################################################################
##  Include folders
#######################################################################################################################################
automation: !include_dir_list Automation/
script: !include_dir_named Script/
sensor: !include_dir_list Sensor/

#######################################################################################################################################
##  Include functions
#######################################################################################################################################
#discovery:
sun:
frontend:
updater:
history:
  exclude:
    domains:
      - automation
logbook:
config:
recorder:
  #db_url: !secret db
  purge_days: 7
  exclude:
    domains:
      - sun
      - updater
    entities:
      - sun.sun
logger:
  default: warning
  logs:
    homeassistant.core: error
    
google:
 client_id: !secret googleid
 client_secret: !secret googlesecret

#######################################################################################################################################
# End of configuration file
#######################################################################################################################################
