###############################
##  Default config
###############################
homeassistant:
  name: HASS
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

###############################
##  Include files
###############################
#alert: !include Include/alert.yaml
#scene: !include Include/scene.yaml
binary_sensor: !include Include/binary_sensor.yaml
camera: !include Include/camera.yaml
device_tracker: !include Include/device_tracker.yaml
http: !include Include/http.yaml
ifttt: !include Include/ifttt.yaml
input_boolean: !include Include/input_boolean.yaml
media_player: !include Include/media_player.yaml
mqtt: !include Include/mqtt.yaml
netatmo: !include Include/netatmo.yaml
notify: !include Include/notify.yaml
panel_iframe: !include Include/panel_iframe.yaml
shell_command: !include Include/shell.yaml
switch: !include Include/switch.yaml
tts: !include Include/tts.yaml
wemo: !include Include/wemo.yaml

###############################
##  Include folders
###############################
automation: !include_dir_list Automation/
group: !include_dir_named Groups/
input_select: !include_dir_named Input/Select/
script: !include_dir_named Script/
sensor: !include_dir_list Sensor/

###############################
##  Include functions
###############################
#discovery:
frontend:
updater:
hello_state:
history:
logbook:
config:
recorder:
  purge_days: 3

###############################
##  Zones
###############################
zone:
  name: Home
  latitude: !secret z1la
  longitude: !secret z1lo
  radius: 30
  icon: mdi:home
zone 2:
  name: Skole
  latitude: !secret z2la
  longitude: !secret z2lo
  radius: 250
  icon: mdi:school
zone 3:
  name: Jobb
  latitude: !secret z3la
  longitude: !secret z3lo
  radius: 80
  icon: mdi:account-multiple
