homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  time_zone: Europe/Oslo
  packages: !include_dir_named packages
  customize:
    sun.sun:
      hidden: true
    sensor.yr_symbol:
      hidden: true
    group.all_automations:
      hidden: false
ios:    
config:
hassio:
updater:
conversation:
recorder:
history:
logbook:
sun:
