###############################
##  Default config
###############################
homeassistant:
  name: HASS
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include Include/customize.yaml
http:
  api_password: !secret apipassword
  base_url: !secret baseurl
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

###############################
##  Include files
###############################
#alert: !include Include/alert.yaml
#mqtt: !include Include/mqtt.yaml
#scene: !include Include/scene.yaml
shell_command: !include Include/shell.yaml
camera: !include Include/camera.yaml
device_tracker: !include Include/device_tracker.yaml
ifttt: !include Include/ifttt.yaml
input_boolean: !include Include/input_boolean.yaml
media_player: !include Include/media_player.yaml
netatmo: !include Include/netatmo.yaml
notify: !include Include/notify.yaml
panel_iframe: !include Include/panel_iframe.yaml
sensor: !include Include/sensor.yaml
tts: !include Include/tts.yaml
wemo: !include Include/wemo.yaml

###############################
##  Include folders
###############################
#input_slider: !include_dir_named Input_slider/
automation: !include_dir_list Automation/
group: !include_dir_named Groups/
input_select: !include_dir_named Input_select/
script: !include_dir_named Script/

###############################
##  Include functions
###############################
#discovery:
frontend:
updater:
conversation:
history:
logbook:
config:
recorder:
  purge_days: 3

###############################
##  Zones
###############################
zone:
  name: Home
  latitude: !secret z1la
  longitude: !secret z1lo
  radius: 30
  icon: mdi:home
zone 2:
  name: Skole
  latitude: !secret z2la
  longitude: !secret z2lo
  radius: 250
  icon: mdi:school
zone 3:
  name: Jobb
  latitude: !secret z3la
  longitude: !secret z3lo
  radius: 80
  icon: mdi:account-multiple
