###############################
##  Default config
###############################
homeassistant:
  name: HASS
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include include/customize.yaml
http:
  api_password: !secret apipassword
  base_url: !secret baseurl
  
###############################
##  Include files
###############################
#alert: !include include/alert.yaml
#scene: !include include/scene.yaml
#shell_command: !include include/shell.yaml
automation: !include include/automation.yaml
camera: !include include/camera.yaml
device_tracker: !include include/device_tracker.yaml
ifttt: !include include/ifttt.yaml
input_boolean: !include include/input_boolean.yaml
media_player: !include include/media_player.yaml
mqtt: !include include/mqtt.yaml
netatmo: !include include/netatmo.yaml
notify: !include include/notify.yaml
panel_iframe: !include include/panel_iframe.yaml
script: !include include/script.yaml
sensor: !include include/sensor.yaml
tts: !include include/tts.yaml

###############################
##  Include folders
###############################
group: !include_dir_named group/
input_select: !include_dir_named input_select/

###############################
##  Include functions
###############################
wemo:
frontend:
updater:
discovery:
conversation:
history:
logbook:
config:

###############################
##  Zones
###############################
zone:
  name: Home
  latitude: !secret z1la
  longitude: !secret z1lo
  radius: 30
  icon: mdi:home
zone 2:
  name: Skole
  latitude: !secret z2la
  longitude: !secret z2lo
  radius: 250
  icon: mdi:school
zone 3:
  name: Jobb
  latitude: !secret z3la
  longitude: !secret z3lo
  radius: 80
  icon: mdi:account-multiple