homeassistant:
  name: JARVIS
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 200
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages
frontend:
config:
updater:
hassio:
conversation:
history:
logbook:
sun:
tts:
  platform: google
switch:
  - platform: rpi_gpio
    ports:
      20: "Desk Lamp"