#######################################################################################################################################
##  Default config
#######################################################################################################################################
homeassistant:
  name: Jarvis
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages
#######################################################################################################################################
config:
#######################################################################################################################################  
frontend:
####################################################################################################################################### 
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            authenticationRequired: no
            destructive: yes
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            authenticationRequired: no
            destructive: yes

#######################################################################################################################################
logbook:
#######################################################################################################################################  
sun:
#######################################################################################################################################  
updater:
#######################################################################################################################################