############################################################################
##  Base `configuration.yaml` most stuff is in ./packages/*.yaml
############################################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  time_zone: Europe/Oslo
  packages: !include_dir_named packages
############################################################################
  customize:
    sun.sun:
      hidden: true
    sensor.yr_symbol:
      hidden: true
    group.all_automations:
      hidden: true
    group.al_scripts:
      hidden: true
############################################################################
ios:
config:
updater:
conversation:
recorder:
history:
logbook:
sun:
############################################################################

