homeassistant:
  name: JARVIS
  latitude: 60.8833
  longitude: 11.5667
  elevation: 200
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages
frontend:
config:
updater:
discovery:
conversation:
history:
logbook:
sun:
tts:
  platform: google
switch:
  - platform: rpi_gpio
    ports:
      20: "Desk Lamp"