homeassistant:
  {
    'name': 'HassBOX',
    'latitude': 0,
    'longitude': 0,
    'elevation': 0,
    'unit_system': 'metric',
    'time_zone': 'UTC'
  }

frontend:
config:
hassio:
conversation:
history:
logger:
  {
    'default': 'info'
  }
logbook:
map:
sun:
cloud:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

binary_sensor: [
  {
    'platform': 'ping',
    'name': 'Netatmo Welcome',
    'host': '192.168.2.203',
    'count': 3,
    'scan_interval': 30
  }
]

influxdb:
  {
    'host': '192.168.2.200',
    'port': 8086,
    'username': 'homeassistant',
    'password': 'homeassistant',
    'database': 'homeassistant'
  }

sensor: [
  {
    'platform': 'version',
    'source': 'hassio',
    'name': 'Published Hass.io version'
  },
  {
    'platform': 'version',
    'name': 'Installed Hass.io version'
  },
  {
    'platform': 'speedtest',
    'minute': [0, 10, 20, 30, 40, 50],
    'monitored_conditions': ['ping', 'download', 'upload']
  }
]

wemo: 
  {
    'discovery': false,
    'static': ['192.168.2.106']
  }