############################################################################
##  Base `configuration.yaml` most stuff is in packages/*.yaml
############################################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  time_zone: Europe/Oslo
  packages: !include_dir_named packages
############################################################################
ios:
discovery:
config:
updater:
conversation:
history:
logbook:
sun:
############################################################################
http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
    - 192.168.2.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
