auth: # https://developers.home-assistant.io/blog/2018/07/02/trying-new-auth.html

automation: !include automations.yaml # https://www.home-assistant.io/docs/automation/

config: # https://www.home-assistant.io/components/config/

hassio: # https://www.home-assistant.io/hassio/installation/#migrating-from-a-non-hassio-install

frontend: # https://www.home-assistant.io/components/frontend/

group: !include groups.yaml # https://www.home-assistant.io/components/group/

history: # https://www.home-assistant.io/components/history/

homeassistant: # https://www.home-assistant.io/docs/configuration/basic/
  name: Home Assistant
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 5
  unit_system: metric
  time_zone: Europe/Oslo
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

http: # https://www.home-assistant.io/components/http/
  api_password: !secret http_api_password
  use_x_forwarded_for: true
  trusted_proxies:
   - 192.168.2.11

logbook: # https://www.home-assistant.io/components/logbook/

logger: # https://www.home-assistant.io/components/logger/
  default: warn
  logs:
    custom_components: debug

media_player:
  - platform: spotify # https://www.home-assistant.io/components/media_player.spotify/
    client_id: !secret media_player_spotify_client_id
    client_secret: !secret media_player_spotify_client_secret
    scan_interval: 5

netatmo: # https://www.home-assistant.io/components/netatmo/
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

script: !include scripts.yaml # https://www.home-assistant.io/docs/scripts/

sensor core:
  - platform: netatmo # https://www.home-assistant.io/components/sensor.netatmo/
    station: BAZINGA
    modules:
      Inne:
        - temperature
        - max_temp

updater: # https://www.home-assistant.io/components/updater/
  include_used_components: true

###################################################
###        CUSTOM COMPONENTS / PLATFORMS:       ###
###################################################
custom_updater: # https://github.com/custom-components/custom_updater

usps_mail: # https://github.com/custom-components/usps_mail
  provider: gmail
  email: !secret usps_mail_email
  password: !secret usps_mail_password
  output_dir: '/config/www/USPS/'

sensor custom:
  - platform: authenticated # https://github.com/custom-components/sensor.authenticated
    exclude:
      - 172.30.32.2
      - 192.168.2.11
  - platform: rpi_power # https://github.com/custom-components/sensor.rpi_power
    text_state: True
  - platform: tautulli # https://github.com/custom-components/sensor.tautulli
    host: 192.168.2.11
    port: 32867
    api_key: !secret sensor_tautulli_api_key
    attributes:
      - title
      - grandparent_title
      - parent_title
      - media_index
      - player
      - show_senum
      - s_senum_e
      - senum
  - platform: untappd # https://github.com/custom-components/sensor.untapped
    username: !secret sensor_untappd_username
    id: !secret sensor_untappd_id
    secret: !secret sensor_untappd_secret

sickrage: # https://github.com/custom-components/sickrage
  host: 'http://192.168.2.236:8081/api'
  api_key: !secret sickrage_api_key