#######################################################################################################################################
##  Default config
#######################################################################################################################################
homeassistant:
  name: Jarvis
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages
#######################################################################################################################################
config:
#######################################################################################################################################  
frontend:
#######################################################################################################################################  
logbook:
#######################################################################################################################################  
sun:
#######################################################################################################################################  
updater:
#######################################################################################################################################