############################################################################
##  Base `configuration.yaml` most stuff is in packages/*.yaml
############################################################################
homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Oslo
  packages: !include_dir_named packages
############################################################################
http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret base_url
############################################################################
discovery:
config:
updater:
  include_used_components: true
conversation:
history:
logbook:
homekit:
  auto_start: False
cloud:
automation for_homekit:
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:01
      - service: homekit.start
map:
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.0/24
ios:
hassbian_config:
switch:
  - platform: hadockermon
    host: 192.168.2.11
recorder:
  purge_keep_days: 30
  db_url: !secret db_url
############################################################################
##  Hubs
############################################################################
netatmo:
  api_key: !secret netatmo_key
  secret_key: !secret netatmo_secret
  username: !secret gmail
  password: !secret netatmo_password
  discovery: false
#---------------------------------------------------------------------------
mqtt:
  broker: !secret mqtt-broker
  port: 1883
  username: !secret mqtt-user
  password: !secret mqtt-pass
############################################################################
