###############################
##  Default config
###############################
homeassistant:
  name: Home
  latitude: !secret z1la
  longitude: !secret z1lo
  elevation: 221
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include include/customize.yaml
http:
  api_password: !secret apipassword
  base_url: !secret baseurl
  
###############################
##  Include files
###############################
#alert: !include include/alert.yaml
#scene: !include include/scene.yaml
#shell_command: !include include/shell.yaml
group: !include include/group.yaml
mqtt: !include include/mqtt.yaml
script: !include include/script.yaml
automation: !include include/automation.yaml
media_player: !include include/media_player.yaml
notify: !include include/notify.yaml
ifttt: !include include/ifttt.yaml
device_tracker: !include include/device_tracker.yaml
netatmo: !include include/netatmo.yaml

###############################
##  Include functions
###############################
wemo:
frontend:
updater:
discovery:
conversation:
history:
logbook:

###############################
##  Zones
###############################
zone:
  name: Hjemme
  latitude: !secret z1la
  longitude: !secret z1lo
  radius: 30
  icon: mdi:home
zone 2:
  name: Skole
  latitude: !secret z2la
  longitude: !secret z2lo
  radius: 250
  icon: mdi:school
zone 3:
  name: Jobb
  latitude: !secret z3la
  longitude: !secret z3lo
  radius: 80
  icon: mdi:account-multiple

shell_command: 
  gitpush:  sudo ./home/pi/hassbian-scripts/gitpush.sh