#######################################################################################################################################
##  During startup of Home Assistant
#######################################################################################################################################
homeassistant:
  customize:
    automation.automation_for_when_jarvis_starts:
      hidden: true
#######################################################################################################################################
automation:
  - alias: "Automation for when 'Jarvis' starts"
    initial_state: "on"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.pushbullet
        data:
          title: "JARVIS"
          message: "Jarvis started successfully."
#######################################################################################################################################

#######################################################################################################################################
