homeassistant:
  customize:
    sensor.avgang:
      hidden: true
    sensor.avgang_source:
      hidden: true
    sensor.linje__retning:
      hidden: true
    sensor.nestebuss:
      icon: mdi:bus
group:
  nestebuss:
    name: '# Ruter'
    entities:
      - sensor.nestebuss

sensor:
  - platform: rest
    resource: http://reisapi.ruter.no/StopVisit/GetDepartures/2190255
    name: Linje - Retning
    value_template: '{{ value_json[0].MonitoredVehicleJourney.LineRef }} - {{ value_json[0].MonitoredVehicleJourney.DestinationName }}'
  - platform: rest
    resource: http://reisapi.ruter.no/StopVisit/GetDepartures/2190255
    name: Avgang_source
    value_template: '{{ value_json[0].MonitoredVehicleJourney.MonitoredCall.ExpectedDepartureTime }}'
  - platform: yr
  - platform: template
    sensors:
      avgang:
        value_template: '{% set uptime = (as_timestamp(states.sensor.avgang_source.state))-as_timestamp(now()) | int %}{% set minutes = ((uptime % 3600) / 60) | int %}Om {{ "%02d" % minutes}} minutter'
      nestebuss:
        friendly_name: 'Neste Buss'
        value_template: '{{states.sensor.linje__retning.state}}:  {{states.sensor.avgang.state}}'