resources:
  - url: /local/monster-card.js
    type: js
views:
  - name: Second view
    cards:
      - type: custom:monster-card
        card:
          type: glance
          title: Monster
        filter:
          include:
            - domain: switch