cch:
  exceptions:
  - conditions:
      user: ControlBox User
    config:
      default_tab: '1'
      disable_sidebar: false
      hide_tabs: []
      kiosk_mode: true
      menu: show
      notifications: show
      options: show
      show_tabs: '1'
      voice: show
resources:
- type: module
  url: /community_plugin/compact-custom-header/compact-custom-header.js
- type: module
  url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
- type: js
  url: /community_plugin/favicon-counter/favicon-counter.js
title: Area 51
views:
- badges: []
  cards:
  - entities:
    - entity: input_boolean.system_restart
    - entity: input_boolean.system_upgrade
    show_header_toggle: false
    title: System information
    type: entities
  - entities:
    - entity: sensor.hacs
    show_header_toggle: false
    type: entities
  path: default_view
  title: Home
- badges: []
  cards:
  - entity: weather.area_51
    type: weather-forecast
  - entity: media_player.spotify
    type: media-control
  - entities:
    - entity: sensor.entur_solvikveien_platform_7099
      name: Rettning Oslo
    - entity: sensor.entur_solvikveien_platform_7101
      name: Rettning Rykkin
    show_header_toggle: false
    title: Neste buss avgang
    type: entities
  panel: false
  path: controllbox
  title: ControllBox
- badges: []
  cards:
  - entities:
    - color: blue
      entity: sensor.adguard_dns_queries
      name: Queries
    - color: red
      entity: sensor.adguard_dns_queries_blocked
      name: Blocked
    icon: mdi:server
    name: AdGuard DNS Queries
    type: custom:mini-graph-card
  path: stats
  title: Stats
