############################################################################
##  Guest mode
############################################################################
homeassistant:
  customize:
    switch.guest_mode:
      icon: mdi:account-off
############################################################################
switch:
  - platform: mqtt
    name: "Guest mode"
    state_topic: "boolean/guest_mode"
    command_topic: "boolean/guest_mode"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

automation:
  alias: "Activate Guest Docker container for HA for guests."
  trigger:
    - platform: state
      entity_id: switch.guest_mode
  action:
    - service_template: 'switch.turn_{{ trigger.to_state.state }}'
      entity_id: switch.homeassistantguest
