############################################################################
##  Not home mode
############################################################################
homeassistant:
  customize:
    switch.not_home:
      icon: mdi:home-outline
############################################################################
switch:
  - platform: mqtt
    name: "Not Home"
    state_topic: "boolean/not_home"
    command_topic: "boolean/not_home"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
