############################################################################
##  Vacation mode
############################################################################
homeassistant:
  customize:
    switch.vacation_mode:
      icon: mdi:airplane-takeoff
############################################################################
switch:
  - platform: mqtt
    name: "Vacation mode"
    state_topic: "boolean/vacation_mode"
    command_topic: "boolean/vacation_mode"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
