############################################################################
##  Workday mode
############################################################################
  workday_tomorrow:
    name: "Workday Tomorrow"
    icon: mdi:factory
############################################################################
automation:
  - alias: "Activate 'Workday Tomorrow mode'"
    initial_state: !secret automation
    trigger:
      platform: time
      at: "20:00:00"
    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.workday_tomorrow
#---------------------------------------------------------------------------
  - alias: "Deactivate 'Workday Tomorrow mode'"
    initial_state: !secret automation
    trigger:
      - platform: time
        at: "20:00:00"
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: "on"
    condition:
      - condition: time
        weekday:
          - fri
          - sat
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.workday_tomorrow
