############################################################################
##  Workday mode
############################################################################
homeassistant:
  customize:
    switch.workday_tomorrow:
      icon: mdi:factory
############################################################################
switch:
  - platform: mqtt
    name: "Workday Tomorrow"
    state_topic: "boolean/workday_tomorrow"
    command_topic: "boolean/workday_tomorrow"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
############################################################################
automation:
  - alias: "Activate 'Workday Tomorrow mode'"
    initial_state: !secret automation
    trigger:
      platform: time
      at: "20:00:00"
    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: switch.vacation_mode
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "boolean/workday_tomorrow"
          message: "ON"
          retain: true
#---------------------------------------------------------------------------
  - alias: "Deactivate 'Workday Tomorrow mode'"
    initial_state: !secret automation
    trigger:
      - platform: time
        at: "20:00:00"
      - platform: state
        entity_id: switch.vacation_mode
        to: "on"
    condition:
      - condition: time
        weekday:
          - fri
          - sat
    action:
      - service: mqtt.publish
        data:
          topic: "boolean/workday_tomorrow"
          message: "OFF"
          retain: true
