install_suite:
  description: Installs a suite with hassbian-config.
  fields:
    suite:
      description: '(recuired) Can be one of: hue, cloud9, tradfri, samba, appdaemon.'
      example: hue
upgrade_suite:
  description: Upgrades a suite with hassbian-config.
  fields:
    suite:
      description: '(recuired) Can be one of: appdaemon, cloud9, hassbian-script'
      example: hassbian-script
    beta:
      description: '(optional) Can be true true or false, defaults to false'
      example: false
    dev:
      description: '(optional) Can be true true or false, defaults to false'
      example: false
