#######################################################################################################################################
##  Studd on the desk
#######################################################################################################################################
homeassistant:
  customize:
    switch.desk_lamp:
      icon: mdi:lightbulb
switch:
  - platform: rpi_gpio
    ports:
      17: 'Desk Lamp'