#######################################################################################################################################
##  GUI - Stuff that don't belong in other files.
#######################################################################################################################################
homeassistant:
  customize:
    group.view_master:
      icon: mdi:home
#######################################################################################################################################
group:
#Groups:
  admin:
    control: hidden
    entities:
      - script.restart
      - input_boolean.privacy_mode
      - switch.rf05
  battery:
    control: hidden
    entities:
      - sensor.battery_iphone
      - sensor.battery_ipad
      - sensor.battery_android
      - sensor.battery_netatmo
  enheter:
    control: hidden
    entities:
      - sensor.template_iphone
      - sensor.template_android_sgs7e
      - device_tracker.ipad
  master:
    control: hidden
    entities:
      - sensor.netatmo_ute_temperature
      - sensor.netatmo_inne_temperature
      - script.goodnight
      - switch.rf01
      - switch.rf02
      - switch.rf03
      - switch.rf04
      - switch.rf06
      - switch.desk_lamp
  
#Views:
  view_master:
    control: hidden
    view: true
    entities:
      - group.radio
      - group.master
#######################################################################################################################################
panel_iframe:
  router:
    title: 'Router'
    url: !secret url-router
    icon: mdi:router-wireless

  plex:
    title: 'PLEX'
    url: !secret url-plex
    icon: mdi:plex
    
  glances_winbox:
    title: 'Glances - WinBOX'
    url: http://192.168.1.10:61208/
    icon: mdi:server