#######################################################################################################################################
##  Home Assistant Uptime and Version
##  Original by: torn8o https://github.com/torn8o
#######################################################################################################################################
homeassistant:
  customize:
    sensor.ha_current_version:
      entity_picture: https://home-assistant.io/demo/favicon-192x192.png
    sensor.ha_installed_version:
      entity_picture: https://home-assistant.io/demo/favicon-192x192.png
    sensor.ha_last_restart:
      icon: mdi:power
#######################################################################################################################################
sensor:
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: HA Current Version
  - platform: command_line
    name: HA Installed Version
    command: /srv/homeassistant/bin/hass --version
  - platform: template
    sensors:
      ha_last_restart:
        value_template: '{{ as_timestamp(states.automation.automation_for_when_jarvis_starts.attributes.last_triggered) | timestamp_custom("%d %b %X") }}'
        friendly_name: HA Last Restart
#######################################################################################################################################
automation:
  - alias: 'Update Available Notification'
    hide_entity: true
    trigger:
      platform: template
      value_template: '{% if (states.sensor.ha_installed_version.state) != (states.sensor.ha_current_version) %}true{% else%}false{% endif %}'
    action:
      - service: notify.pushbullet
        data:
          title: 'Jarvis'
          message: 'Update for Home Assistant is available.'
      - service: persistent_notification.create
        data:
          message: 'Update for Home Assistant is available.'
          title: 'Home Assistant Update'
          notification_id: '1234'
#######################################################################################################################################
group:
  hass:
    name: 'Home Assistant'
    entities:
      - sensor.ha_installed_version
      - sensor.ha_current_version
      - sensor.ha_last_restart

shell_command:
  upgrade_ha: 'pip3 install --upgrade homeassistant && ssh pi@192.168.1.2 hassctl restart'