#######################################################################################################################################
##  Stuff that don't belong anywhere else.
#######################################################################################################################################
homeassistant:
  customize:
    group.all_automations:
      control: hidden
      hidden: false
      friendly_name: 'Automations'
    group.all_scripts:
      control: hidden
      hidden: false
      friendly_name: 'Script'
#######################################################################################################################################
shell_command:
  updatefromgit: cd /home/homeassistant/.homeassistant && git pull https://github.com/ludeeus/hass-config
#######################################################################################################################################
input_boolean:
  privacy_mode:
    name: Privacy Mode
    initial: on
    icon: mdi:volume-off
#######################################################################################################################################
sensor:
  - name: cn_joke
    platform: rest
    resource: http://api.icndb.com/jokes/random?firstName=Joakim&lastName=Sorensen
    value_template: '{{ value_json.value.joke }}'
#######################################################################################################################################
script:
  send_joke:
    alias: Send CN Joke
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.cast_audio
          message: '{{states.sensor.cn_joke.state}}'
          language: 'en'
      - service: notify.pushbullet
        data_template:
          title: 'Le litt da :)'
          message: '{{states.sensor.cn_joke.state}}'
  restart:
    alias: 'Restart Jarvis'
    sequence:
      - service: script.tts
        data:
          message: restarter hass
#      - service: shell_command.updatefromgit
      - service: homeassistant.restart
  tts:
    alias: TTS
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.cast_audio
          message: "{{message}}"
  updatefromgit:
    alias: Update files from git
    sequence:
      - service: shell_command.updatefromgit