#######################################################################################################################################
##  Web radio
#######################################################################################################################################
automation:
  alias: 'Sunset Automations'
  trigger:
    platform: sun
    event: sunset
#    offset: '00:30:00'
  action:
    service: switch.turn_on
    entity_id: 
      - switch.rf02
      - switch.desk_lamp