#######################################################################################################################################
##  Web radio
#######################################################################################################################################
homeassistant:
  customize:
    script.webradio_start:
      friendly_name: Start webradio
      hidden: true
    script.webradio_stop:
      friendly_name: Stop webradio
      hidden: true
    input_select.radio:
      icon: mdi:radio
#######################################################################################################################################
automation:
  - alias: 'Web-radio in the livingroom'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.radio
    action:
      - service_template: script.turn_on
        data_template:
          entity_id: 'script.webradio_{%if is_state("input_select.radio","Stopp")%}stop{%else%}start{%endif%}'
#######################################################################################################################################
group:
  radio:
    control: hidden
    entities:
      - input_select.radio
#######################################################################################################################################
script:
  webradio_start:
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.chrome_cast
          media_content_id: >
            {% if is_state("input_select.radio", "P4") %}
              http://stream.p4.no/p4_aac_lq
            {%-elif is_state("input_select.radio", "Radio Norge") %}
              http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
            {%-elif is_state("input_select.radio", "Solør Radio") %}
              http://109.169.96.11:8000/solor.mp3
            {% else %}
            {% endif %}
          media_content_type: 'audio/mp4'
      - service: media_player.turn_on
        entity_id: media_player.yamaha_receiver
  webradio_stop:
    sequence:
      - service: media_player.media_stop
        entity_id: media_player.chrome_cast
#######################################################################################################################################
input_select:
  radio:
    name: Velg radiokanal
    options:
      - 'Stopp'
      - 'P4'
      - 'Radio Norge'
      - 'Solør Radio'
    initial: 'Stopp'
