#######################################################################################################################################
##  Devices / Android
#######################################################################################################################################
sensor:
  platform: template
  sensors:
    battery_android:
      friendly_name: Android
      unit_of_measurement: '%'
      value_template: >
          {%- if states.device_tracker.mqtt_android.attributes.battery %}
              {{ states.device_tracker.mqtt_android.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_android.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.battery_android", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.mqtt_android", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.mqtt_android.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.mqtt_android.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.mqtt_android.attributes.battery|float / 10)|round*10}}{%- endif %}'
#######################################################################################################################################

#######################################################################################################################################

#######################################################################################################################################
