#######################################################################################################################################
##  Devices / iPad
#######################################################################################################################################
sensor:
  platform: template
  sensors:
    battery_ipad:
      friendly_name: iPad
      unit_of_measurement: '%'
      value_template: >
          {%- if states.device_tracker.ipad.attributes.battery %}
              {{ states.device_tracker.ipad.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_ipad.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.battery_ipad", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.ipad", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.ipad.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.ipad.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.ipad.attributes.battery|float / 10)|round*10}}{%- endif %}'
#######################################################################################################################################

#######################################################################################################################################

#######################################################################################################################################
