#######################################################################################################################################
##  Devices / iPhone
#######################################################################################################################################
homeassistant:
  customize:
    sensor.iphone_battery_level:
      hidden: true
    sensor.iphone_battery_state:
      hidden: true
    device_tracker.iphone:
      hidden: true
    sensor.phone_to_home:
      hidden: true
#######################################################################################################################################
sensor:
  - platform: template
    sensors:
      template_iphone:
        friendly_name: iPhone 6
        value_template: '{%if (states.device_tracker.iphone.state) != "not_home" %}{{states.device_tracker.iphone.state}}{%- else -%}{{states.sensor.phone_to_home.state}} Minutes to home{%- endif %}'
        icon_template: '{{states.sensor.iphone_battery_level.attributes.icon}}'
#######################################################################################################################################
  - platform: google_travel_time
    name: Phone To Home
    api_key: !secret googleapi
    origin: device_tracker.iphone
    destination: zone.home
#######################################################################################################################################
