#######################################################################################################################################
##  Zones
#######################################################################################################################################
homeassistant:
  customize:
    zone.home:
      icon: mdi:home
    zone.skole:
      icon: mdi:school
    zone.work:
      icon: mdi:account-multiple
#######################################################################################################################################
zone:
  - name: Home
    latitude: !secret z1la
    longitude: !secret z1lo
    radius: 30
    icon: mdi:home

  - name: Skole
    latitude: !secret z2la
    longitude: !secret z2lo
    radius: 250
    icon: mdi:school

  - name: Jobb
    latitude: !secret z3la
    longitude: !secret z3lo
    radius: 80
    icon: mdi:account-multiple