#######################################################################################################################################
##  iOS push - light
#######################################################################################################################################
automation:
  - alias: Notify iOS app
    trigger:
      platform: time
      after: '22:30:00'
    action:
      service: notify.ios_iphone
      data:
        message: "Something happened at home!"
        data:
          push:
            category: 'ALARM'

  - alias: Sound the alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM
    action:
      service: switch.turn_on
      entity_id: switch.desk_lamp