- alias: 'Morgen radio'
  trigger:
    platform: time
    after: '07:00:00'
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.turn_on
    entity_id: script.radio_on_stue