- alias: 'Morgen radio, ukedager 07:00, hjemme'
  trigger:
    platform: time
    after: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: device_tracker.tel_android 
      state: 'Home'
  action:      
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.volume_set
      data:
        entity_id: media_player.yamaha_receiver
        volume_level: 0.40
    - service: script.spotify_stue_start

- alias: 'Varsling lav temp, ukedager 07:03, hjemme'
  initial_state: True
  hide_entity: false
  trigger:
    - platform: time
      after: '07:03:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.netatmo_ute_temperature
      below: '3'
    - condition: state
      entity_id: device_tracker.tel_android 
      state: 'Home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.pushbullet
      data:
        message: 'Det er kaldt! {{ states.sensor.netatmo_ute_temperature.state }} grader, lurt 책 holde seg inne i dag :)'

- alias: Start radio p책 badet
  trigger:
    platform: state
    entity_id: input_select.radio
    to: "Bad"
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.cast_audio
      media_content_id: http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
      media_content_type: audio/mp4
      
- alias: Start radio p책 stua
  trigger:
    platform: state
    entity_id: input_select.radio
    to: "Stua"
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.chrome_cast
      media_content_id: http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
      media_content_type: audio/mp4
      
- alias: Stopp radio p책 stua eller bad
  trigger:
    platform: state
    entity_id: input_select.radio
    to: "Stopp"
  action:
    - service: media_player.turn_off
      entity_id: media_player.cast_audio
    - service: media_player.turn_off
      entity_id: media_player.chrome_cast