- platform: template
  sensors:
    vaskemaskin:
      value_template: '{%-if is_state_attr("switch.w01","current_power_mwh","unknown")%}"Ukjent Status"{% else %}{{ states.switch.w01.attributes.current_power_mwh > 400}}{%- endif %}'
      friendly_name: 'Vaskemaskin'
