- platform: yamaha
  host: 192.168.1.27
  source_ignore:
      - "AUX"
      - "AUDIO"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "NET RADIO"
      - "SERVER"
      - "TUNER"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
  source_names:
    HDMI2: "ATV"
    Spotify: "SPOTIFY"
- platform: lg_netcast
  host: 192.168.1.22
  access_token: 221540
- platform: plex
  host: 192.168.1.10
- platform: apple_tv
  host: 192.168.1.21
  login_id: 00000000-3d15-ff02-7dfe-85f64ead4cd2
  name: ATV Soverommet
- platform: apple_tv
  host: 192.168.1.20
  login_id: 00000000-3d15-ff02-7dfe-85f64ead4cd2
  name: ATV Stua
- platform: cast
  host: 192.168.1.25
- platform: cast
  host: 192.168.1.26
