- platform: yamaha
- platform: lg_netcast
  host: 192.168.1.217
  access_token: 221540
- platform: plex
  host: 192.168.1.10
- platform: apple_tv
  host: 192.168.1.147
  login_id: 00000000-3d15-ff02-7dfe-85f64ead4cd2
  name: ATV Soverommet
- platform: apple_tv
  host: 192.168.1.146
  login_id: 00000000-3d15-ff02-7dfe-85f64ead4cd2
  name: ATV Stua
