- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload
    
- platform: google_travel_time
  name: Phone To Home
  api_key: !secret googleapi
  origin: device_tracker.iphone
  destination: zone.home
  
- platform: template
  sensors:
    battery_iphone:
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.iphone.attributes.battery %}
              {{ states.device_tracker.iphone.attributes.battery }}
          {% else %}
              {{ states.sensor.battery_iphone.state }}
          {%- endif %}