- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload
    
- platform: google_travel_time
  name: Phone To Home
  api_key: !secret googleapi
  origin: device_tracker.tel_android
  destination: zone.Hjemme