- platform: template
  switches:
    stua:
      value_template: "{{ states.switch.w01.state }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.w01
        - service: media_player.turn_on
          entity_id: media_player.cast_audio
      turn_off:
        - service: switch.turn_off
          entity_id: switch.w01
        - service: media_player.turn_off
          entity_id: media_player.cast_audio
