- platform: mqtt
  name: "rf01"
  state_topic: "HA/RF"
  command_topic: "HA/RF"
  payload_on: "14501204"
  payload_off: "14501201"
  
- platform: mqtt
  name: "rf02"
  state_topic: "HA/RF"
  command_topic: "HA/RF"
  payload_on: "14504276"
  payload_off: "14504273"
  
- platform: mqtt
  name: "rf03"
  state_topic: "HA/RF"
  command_topic: "HA/RF"
  payload_on: "14505044"
  payload_off: "14505041"
  
- platform: mqtt
  name: "rf04"
  state_topic: "HA/RF"
  command_topic: "HA/RF"
  payload_on: "14505236"
  payload_off: "14505233"
  
- platform: mqtt
  name: "rf05"
  state_topic: "HA/RF"
  command_topic: "HA/RF"
  payload_on: "16598356"
  payload_off: "16598353"
  
- platform: mqtt
  name: "rf06"
  state_topic: "HA/RF"
  command_topic: "HA/RF"
  payload_on: "16601428"
  payload_off: "16601425"
