alias: Alert
initial_state: 'on'
trigger:
  - platform: state
    entity_id: switch.rf01
    to: 'on'
action:
  - service: persistent_notification.create
    data_template:
      title: "Alert"
      message: '{{("trigger.entity_id".split("."))[1]}}'
