alias: Automatic turn off bed nightlight after 3 minutes
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf04
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.privacy_mode
    state: 'off'
action:
  - delay:
      seconds: 180
  - service: input_boolean.turn_off
    entity_id: input_boolean.rf04
