alias: Update notifications
initial_state: 'on'
trigger:
  - platform: state
    entity_id: updater.updater
action:
  service: notify.pushbullet
  data:
    title: 'Jarvis'
    message: 'There is a new Home Assistant release available.'
