alias: Master Volume
trigger:
  platform: state
  entity_id: input_select.test_slider
  to: CUSTOM
action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.yamaha_receiver
      volume_level: '{{ states.input_slider.test_slider.state | int }}'
