alias: Mute Volume during comersials on ChromeCast
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.cccomersial
action:
  - service_template: media_player.volume_set
    data_template:
      entity_id: media_player.yamaha_receiver
      volume_level: '{%- if is_state("sensor.cccomersial", "true")%}0.5{%- else -%}0.7{%- endif %}'