alias: Privacy mode
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.privacy_mode
action:
  - service: tts.google_say
    data_template:
      entity_id: media_player.cast_audio
      message: >
        {% if is_state("input_boolean.privacy_mode", "on") %}
          "Aktivating Privacy mode"
        {% else %}
          "Disabling privacy mode"
        {% endif %}
      language: 'en'
  - delay:
      seconds: 2
  - service: media_player.volume_set
    entity_id: media_player.cast_audio
    data_template:
      volume_level: >
        {% if is_state("input_boolean.privacy_mode", "on") %}
          0
        {% else %}
          0.5
        {% endif %}
