alias: Start radio på stua eller bad
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.radio
action:
  - service: media_player.play_media
    data_template:
      entity_id: media_player.chrome_cast
      media_content_id: >
        {% if is_state("input_select.radio", "P4") %}
          http://stream.p4.no/p4_aac_lq
        {%-elif is_state("input_select.radio", "Radio Norge") %}
          http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
        {%-elif is_state("input_select.radio", "Solør Radio") %}
          http://109.169.96.11:8000/solor.mp3
        {% else %}
          "None"
        {% endif %}
      media_content_type: 'audio/mp4'
  - service: media_player.turn_on
    entity_id: media_player.yamaha_receiver
