alias: Stopp radio på stua eller bad
trigger:
  platform: state
  entity_id: input_select.radio
  to: "Stopp"
action:
  - service: media_player.turn_off
    entity_id: media_player.cast_audio,media_player.chrome_cast