alias: Start radio på badet
trigger:
  platform: state
  entity_id: input_select.radio
  to: "Stua"
action:
  service: media_player.play_media
  data:
    entity_id: media_player.chrome_cast
    media_content_id: http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
    media_content_type: audio/mp4