alias: RF01
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf01
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state("input_boolean.rf01", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    entity_id: switch.rf01
alias: RF02
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf02
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state("input_boolean.rf02", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    entity_id: switch.rf02
alias: RF03
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf03
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state("input_boolean.rf03", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    entity_id: switch.rf03
alias: RF04
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf04
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state("input_boolean.rf04", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    entity_id: switch.rf04
alias: RF05
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf05
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state("input_boolean.rf05", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    entity_id: switch.rf05
alias: RF06
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf06
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state("input_boolean.rf06", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    entity_id: switch.rf06
