alias: RF_Outlet_Controll
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf01
  - platform: state
    entity_id: switch.rf01
  - platform: event
    event_type: homeassistant_start
action:
  - service_template: '{%- if is_state((trigger.entity_id), "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}'
    data_template:
      entity_id: '{{"switch."((trigger.entity_id).split("."))[1]}}'
  - service_template: '{%- if is_state((trigger.entity_id), "on")%}input_boolean.turn_on{% else %}input_boolean.turn_off{%- endif %}'
    data_template:
      entity_id: '{{"input_boolean."((trigger.entity_id).split("."))[1]}}'
