alias: RF01
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.privacy_mode
action:
  - service_template: {%- if is_state("input_boolean.rf01", "on")%}switch.turn_on{% else %}switch.turn_off{%- endif %}
    entity_id: switch.rf01
