alias: 'Set source to ATV if TV goes on.'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.atv_stua
    from: "paused"
    to: "playing"
  - platform: state
    entity_id: switch.rf06
    from: "off"
    to: "on"
action:
  - service: switch.turn_on
    data:
      entity_id: switch.rf06
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha_receiver
      source: 'HDMI2'
