alias: 'Alert when washer is done'
initial_state: 'on'
trigger:
  platform: state
  entity_id: switch.rf06
  from: "off"
  to: "on"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha_receiver
      source: 'HDMI 2'
