alias: Notify when garageport is activated
initial_state: 'on'
trigger:
  - platform: event
    event_type: service_registered
    entity_data: {'entity_id': 'script.send_joke', 'domain': 'homeassistant'}
action:
  - service: notify.pushbullet
    data:
      title: 'Jarvis'
      message: 'Garageport is activated.'
