alias: Skru av TV når Yamaha stopper
trigger:
  - platform: state
    entity_id: media_player.
    to: 'off'
action:
  - service: media_player.turn_off
    entity_id: media_player.lg_tv_remote
