alias: Skru av TV når ATV starter
trigger:
  - platform: state
    entity_id: media_player.atv_stua
    to: 'off'
action:
  - service: media_player.turn_off
    entity_id: media_player.lg_tv_remote
