alias: 'Morgen radio, ukedager 07:00, hjemme'
trigger:
  platform: time
  after: '07:00:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: device_tracker.iphone 
    state: 'home'
action:      
  - service: media_player.turn_on
    entity_id: media_player.yamaha_receiver
  - service: media_player.volume_set
    data:
      entity_id: media_player.yamaha_receiver
      volume_level: 0.40
  - service: script.spotify_stue_start
  - service: media_player.play_media
    data:
      entity_id: media_player.cast_audio
      media_content_id: http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
      media_content_type: audio/mp4