############################################################################
##  Alarm panal
############################################################################
sensor:
  - platform: mqtt
    name: "Alarm"
    state_topic: "homeassistant/alarm_control_panel/house/state"
############################################################################
panel_custom:
   - name: alarm
     sidebar_title: Alarm
     sidebar_icon: mdi:security-home
     config:
       alarmid: alarm_control_panel.house ## USE THE SAME ID AS USED IN YOUR ALARM.YAML
############################################################################
alarm_control_panel:
  platform: bwalarm
  name: House
  code: !secret alarm_code
  pending_time: 25 #Grace time in seconds to allow for exit and entry using Away mode
  trigger_time: 600
  alarm: automation.alarm_detected
  warning: automation.alarm_warning
  clock: True  #Optional - True enables a clock in the center of the status bar
  perimeter_mode: False #Optional - True enables perimeter mode, this could be known as 'Day Mode' i.e. only arm the doors whilst there is someone using all floors
  weather: True #Optional - Allows a weather summary to be displayed on the status bar. Dark Sky weather component must be enabled with the name sensor.dark_sky_summary
  warning_colour: 'orange'
  pending_colour: 'orange'
  disarmed_colour: '#03A9F4'
  armed_home_colour: 'black'
  armed_away_colour: 'black'
  triggered_colour: 'red'
  immediate:
    - binary_sensor.pir_livingroom
############################################################################
automation:
  - alias: "Alarm activating."
    initial_state: !secret automation
    trigger:
      platform: state
      entity_id: sensor.alarm
      to: "pending"
    action:
      - service: homeassistant.turn_off
        entity_id: group.all_lights, switch.rf03
      - service: media_player.turn_off
        entity_id: media_player.lg_tv_remote
      - delay: 00:00:10
      - service: media_player.turn_off
        entity_id: media_player.lg_tv_remote
#---------------------------------------------------------------------------
  - alias: "Alarm activated."
    initial_state: !secret automation
    trigger:
      - platform: state
        entity_id: sensor.alarm
        to: "armed_away"
    action:
      - service: notify.ios_iphone
        data:
          message: 'Alarm armed!'
#---------------------------------------------------------------------------
  - alias: "Alarm detected."
    initial_state: !secret automation
    trigger:
      - platform: state
        entity_id: sensor.alarm
        to: "triggered"
    action:
#      - service: notify.ios_iphone
#        data:
#          message: 'Alarm!'
#          data:
#            push:
#              category: camera
#            entity_id: camera.ncam01
      - service: light.turn_on
        entity_id: light.h02
        data:
          brightness: 255
          rgb_color: [255, 0, 0]
          flash: "long"
#---------------------------------------------------------------------------
  - alias: "Alarm deactivated."
    initial_state: !secret automation
    trigger:
      - platform: state
        entity_id: sensor.alarm
        to: "disarmed"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.rf03
      - service: light.turn_on
        entity_id: group.all_lights
        data:
          brightness: 255
          rgb_color: [255, 180, 71]
