sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: since_last_boot
      - type: process
        arg: hass
      - type: process
        arg: mysqld
    
  - platform: glances
    host: 192.168.1.10
    resources:
      - 'disk_use_percent'
      - 'memory_use_percent'
      - 'processor_load'
  
    
group:
  raspberry_pi:
    entities:
      - sensor.cpuspeed
      - sensor.ram_use
      - sensor.process_hass
      - sensor.process_mysqld
      - sensor.since_last_boot
      - sensor.cpu_use
  winbox:
    entities:
      - sensor.glances_cpu_load
      - sensor.glances_disk_use
      - sensor.glances_ram_use

  equipment:
    view: yes
    entities:
      - group.raspberry_pi
      - group.network_external
      - group.network_internal
      - group.winbox

homeassistant:
  customize:
    group.raspberry_pi:
      friendly_name: 'Raspberry Pi'
    group.winbox:
      friendly_name: 'WinBOX'