############################################################################
##  Hassbian-config information
############################################################################
homeassistant:
  customize:
    binary_sensor.hassbian_version:
      hidden: true
    sensor.hassbian_online:
      friendly_name: "Online version:"
      entity_picture: https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png
    sensor.hassbian_local:
      friendly_name: "Local version:"
      entity_picture: https://upload.wikimedia.org/wikipedia/commons/1/13/DEB_file_format_icon_on_ubuntu.png
############################################################################
group:
  hassbian:
    name: Hassbian-config
    entities:
      - sensor.hassbian_local
      - sensor.hassbian_online
############################################################################
sensor:
  - platform: command_line
    name: hassbian_online
    command: "curl -s https://raw.githubusercontent.com/home-assistant/hassbian-scripts/dev/package/DEBIAN/control | grep Version | awk '{print $2}'"
  - platform: command_line
    name: hassbian_local
    command: "aptitude show hassbian-scripts | grep Version | awk '{print $2}'"
############################################################################
binary_sensor:
  - platform: template
    sensors:
      hassbian_version:
        value_template: >-
          {{ states.sensor.hassbian_online.state|float > states.sensor.hassbian_local.state|float }}
############################################################################
automation:
  - alias: 'Notify when new `hassbian-config` is available'
    trigger:
      - platform: state
        entity_id: binary_sensor.hassbian_version
        from: 'off'
        to: 'on'
    action:
      service: persistent_notification.create
      data:
        title: 'New version of `hassbian-config` is available'
        message: 'Run `sudo hassbian-config upgrade hassbian-script`'
############################################################################
