############################################################################
##  Hassbian: Home-Assistant Upgrade.
##  Picture: https://i.gyazo.com/403859875dbf382f07a5f35f218a80f3.png
##  NB!: This does not work at all... the scripts stops Home-Assistant
##       and that halts the execution of the rest.
############################################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Hassbian: Home-Assistant Upgrade.'
group:
  hassbian:
    name: Upgrade Home-Asssistant
    control: hidden
    entities:
      - input_select.ha_branch
      - input_text.ha_version
      - script.upgrade_homeassistant
input_select:
  ha_branch:
    name: Home-Asssistant Branch
    options:
     - Stable
     - Beta
     - Dev
    initial: Stable
input_text:
  ha_version:
    name: Version
    initial: ""
shell_command:
  upgrade_homeassistant: '{% if is_state("input_select.ha_branch", "Beta") %}"pip install --upgrade -pre homeassistant"{% elif is_state("input_select.ha_branch", "Dev") %}"pip install git+https://github.com/home-assistant/home-assistant@dev"{% elif states.input_text.ha_version.state != "" %}"pip install --upgrade homeassistant=={{states.input_text.ha_version.state}}"{%- else -%}" "{%- endif %}'
script:
  upgrade_homeassistant:
    alias: Start upgrade
    sequence:
      - service: shell_command.upgrade_homeassistant 
      - delay: '00:05:00'
      - service: homeassistant.restart