#######################################################################################################################################
##  Test
#######################################################################################################################################
sensor:
  platform: haveibeenpwned
  email: 
    - !secret hibp1
    - !secret hibp2
    - !secret hibp3