#######################################################################################################################################
##  Test
#######################################################################################################################################
sensor:
  platform: haveibeenpwned
  email: 
    - joasoe@gmail.com
    - joasoe@outlook.com
    - joakim@joakims.net