#######################################################################################################################################
##  Home Assistant - Extention of 'configuration.yaml'
#######################################################################################################################################
homeassistant:
  customize_domain:
    script:
      icon: mdi:settings
    automation:
      icon: mdi:circle-outline
  customize_glob:
    'sensor.glances_*':
      icon: mdi:windows
#######################################################################################################################################
automation: !include_dir_list Automation/
#######################################################################################################################################
#discovery:
#######################################################################################################################################
device_tracker:
  - platform: icloud
    username: !secret ios-user
    password: !secret ios-password
  - platform: owntracks
#######################################################################################################################################
google:
  client_id: !secret googleid
  client_secret: !secret googlesecret
#######################################################################################################################################
history:
  exclude:
    domains:
      - automation
#######################################################################################################################################
ifttt:
  key: !secret ifttt-apikey
#######################################################################################################################################
mqtt:
  broker: 192.168.1.2
  username: !secret mqtt-user
  password: !secret mqtt-password
#######################################################################################################################################
tts:
  - platform: google
    language: 'no'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
#######################################################################################################################################

#######################################################################################################################################  
logger:
  default: warning
  logs:
    homeassistant.core: error
#######################################################################################################################################  
recorder:
  db_url: !secret db
  purge_days: 7
  exclude:
    domains:
      - sun
      - updater
    entities:
      - sun.sun