############################################################################
## HA Sensors, "borrowed" from @dale3h
############################################################################
homeassistant:
  customize:
    sensor.avgang:
      hidden: true
    sensor.avgang_source:
      hidden: true
    sensor.linje__retning:
      hidden: true
    sensor.nestebuss:
      icon: mdi:bus
############################################################################
group:
  home_assistant:
    name: 'Home-Assistant'
    entities:
      - sensor.ha_version
      - sensor.ha_github_version
      - sensor.ha_pypi_version
############################################################################
sensor:
  - platform: command_line
    name: ha_version
    command: >-
      cat /home/homeassistant/.homeassistant/.HA_VERSION
    scan_interval: 86400
#---------------------------------------------------------------------------
  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name if value_json.tag_name.split('.')|length != 2 else value_json.tag_name ~ '.0' }}
    scan_interval: 1800
#---------------------------------------------------------------------------
  - platform: rest
    name: ha_pypi_version
    resource: 'https://pypi.python.org/pypi/homeassistant/json'
    value_template: >-
      {{ value_json.info.version }}
    scan_interval: 1800
############################################################################
