############################################################################
## Homebridge
############################################################################
homeassistant:
  customize_domain:
    switch:
      homebridge_visible: true
    light:
      homebridge_visible: true
############################################################################
