group:
  media_players:
    view: yes
    entities:
      - media_player.atv_soverommet
      - media_player.atv_stua
      - media_player.cast_audio
      - media_player.chrome_cast
      - media_player.lg_tv_remote
      - media_player.yamaha_receiver

homeassistant:
  customize:
    group.media_players:
      friendly_name: 'Media Players'