#######################################################################################################################################
##  Modes
#######################################################################################################################################
homeassistant:
  customize:
    automation.aktiver_workday_tomorrow:
      hidden: true
    automation.deaktiver_workday_tomorrow:
      hidden: true
#######################################################################################################################################
group:
  modes:
    name: 'Modes'
    entities:
      - input_boolean.vacation_mode
      - input_boolean.guest_mode
      - input_boolean.workday_tomorrow

automation:
  - alias: "Aktiver 'Workday Tomorrow'"
    initial_state: "on"
    trigger:
      platform: time
      at: "20:00:00"
    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.workday_tomorrow
#--------------------------------------------------------------    
  - alias: "Deaktiver 'Workday Tomorrow'"
    initial_state: "on"
    trigger:
      - platform: time
        at: "20:00:00"
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: "on"
    condition:
      - condition: time
        weekday:
          - fri
          - sat
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.workday_tomorrow
#######################################################################################################################################
input_boolean:
  vacation_mode:
    name: "Aktiver 'Vacation mode'"
    icon: mdi:airplane-takeoff
  guest_mode:
    name: "Aktiver 'Guest mode'"
    icon: mdi:account-off
  workday_tomorrow:
    name: "Aktiver 'Workday Tomorrow'"
    icon: mdi:factory