############################################################################
## Packages / Morning routine
##
## @description Turn on lights, coffee and radio in the morning.
## @component   automation, binary_sensor, customize, light, notify, switch
## @license     MIT
## @author      @ludeeus
############################################################################
# This package uses resources from other packages:
# PIR-Sensor: https://github.com/ludeeus/Home-Assistant-Config/blob/master/packages/motion_sensor.yaml
# Modes (Booleans): https://github.com/ludeeus/Home-Assistant-Config/blob/master/packages/modes/
# Notifications: https://github.com/ludeeus/Home-Assistant-Config/blob/master/packages/notify_template.yaml

# The rest of the switches and lights are added to my Home-Assistant by using `discovery:`
# My lights are a combination and Hue and IKEA Trådfri, running of an Hue gen 1 bridge.
# switch.rf03 is en RF outlet connected to my coffee maker.

homeassistant:
  customize:
    switch.morning_routine:
      hidden: true #I want to hide this, it is only used by the automation.

# A dummy MQTT Switch to keep track of the state so automation don't run multiple times.
# Can also be an input_boolean 
switch:
  - platform: mqtt
    name: "Morning Routine"
    state_topic: 'boolean/morning_routine'
    command_topic: 'boolean/morning_routine'
    payload_on: 'on'
    payload_off: 'off'
    retain: true

automation:
  - alias: "Activate morning routine."
    trigger:
      - platform: state
        entity_id: binary_sensor.pir_livingroom
        to: 'on'
    condition:
      - condition: state #check if this has already run.
        entity_id: switch.morning_routine
        state: 'off'
      - condition: state
        entity_id: switch.guest_mode
        state: 'off'
      - condition: state #check if I'm working.
        entity_id: switch.workday_tomorrow
        state: 'off'
      - condition: time
        after: '06:30:00'
        before: '08:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: group.all_lights, switch.rf03
      - service: switch.turn_on
        entity_id: switch.morning_routine
      - service: media_player.play_media
        data:
          entity_id: media_player.living_room_speaker
          media_content_id: 'http://stream.p4.no/p4_mp3_hq' #Norwegian radio chanel 'P4'
          media_content_type: 'audio/mp4'
      - service: script.notify
        data:
          message: |
            Good morning sir!
            The lights are on, the coffee is brewing and radio is turning on.

# I want to turn off the dummy switch so this can run the next workday.
# automation: ## This is added on line 34, therefore commented here.
  - alias: 'Deactivate morning routine.'
    trigger:
      - platform: time
        at: '08:05:00'
    condition:
      - condition: state
        entity_id: switch.morning_routine
        state: 'on' # Only run this if there is somethin to do.
    action:
      - service: switch.turn_off
        entity_id: switch.morning_routine