############################################################################
##  Morning Routine
############################################################################
# This is a package, to learn more abour packages se this: https://home-assistant.io/docs/configuration/packages/

# A dummy MQTT Switch to keep track of the state so automation don't run multiple times.
# Can also be an input_boolean
switch:
  - platform: mqtt
    name: "Morning Routine"
    state_topic: "boolean/morning_routine"
    command_topic: "boolean/morning_routine"
    payload_on: "on"
    payload_off: "off"
    retain: true

# This will set an prettier icon for the UI
homeassistant:
  customize:
    switch.morning_routine:
      icon: mdi:sun

# The PIR used for this is in an other package:
# https://github.com/ludeeus/Home-Assistant-Config/blob/master/packages/motion_sensor.yaml

# The rest of the switches and lights are added to my Home-Assistant by using `discovery:`
# My lights are a combination and Hue and IKEA Trådfri, running of an Hue gen 1 bridge.
# switch.rf03 is en RF outlet connected to my coffee maker.

# Turn on light and coffee if the PIR see me on weekdays between 6:30AM and 8:00AM, I also want an notification when this run.
automation:
  - alias: "Activate morning routine."
    trigger:
      - platform: state
        entity_id: binary_sensor.pir_livingroom
        to: "on"
    condition:
      - condition: state #check if this has already run.
        entity_id: switch.morning_routine
        state: "off"
      - condition: state #check if I have guests. source: https://github.com/ludeeus/Home-Assistant-Config/blob/master/packages/modes/guest_mode.yaml
        entity_id: switch.guest_mode
        state: "off"
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: time
        after: "06:30:00"
        before: "08:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id: group.all_lights, switch.rf03
      - service: switch.turn_on #check if this has already run.
        entity_id: switch.morning_routine
      - service: script.notify #source: https://github.com/ludeeus/Home-Assistant-Config/blob/master/packages/notify_template.yaml
        data:
          message: "Good morning! \nThe lights are on, and the coffee is brewing. "

# I want to turn off the dummy switch so this can run the next workday.
# automation: # This is added on line 31, therefore commented here.
  - alias: "Deactivate morning routine."
    trigger:
      - platform: time
        at: "08:05:00"
    condition:
      - condition: state
        entity_id: switch.morning_routine
        state: "on" # Only run this if there is somethin to do.
    action:
      - service: switch.turn_off
        entity_id: switch.morning_routine
