sensor:
  - platform: template
    sensors:
      rpi_prod:
        friendly_name: 'RPi Prod-Device'
        value_template: '{% if is_state("device_tracker.rpi_prod", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: 'mdi: {%- if is_state("device_tracker.rpi_prod", "home") %}lan-connect{% else %}lan-disconnect{%- endif %}'
      rpi_dev:
        friendly_name: 'RPi Dev-Device'
        value_template: '{% if is_state("device_tracker.rpi_dev", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: 'mdi: {%- if is_state("device_tracker.rpi_dev", "home") %}lan-connect{% else %}lan-disconnect{%- endif %}'
      winbox:
        friendly_name: 'WinBOX'
        value_template: '{% if is_state("device_tracker.winbox", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: 'mdi: {%- if is_state("device_tracker.winbox", "home") %}lan-connect{% else %}lan-disconnect{%- endif %}'
      esp8266_1:
        friendly_name: 'MQTT RF-Transmitter (WiFi)'
        value_template: '{% if is_state("device_tracker.esp8266", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: 'mdi: {%- if is_state("device_tracker.esp8266", "home") %}lan-connect{% else %}lan-disconnect{%- endif %}'

device_tracker:
  - platform: ping
    hosts:
      rpi_prod: 192.168.1.2
      rpi_dev: 192.168.1.3
      winbox: 192.168.1.10     
      ESP8266: 192.168.1.127
        
        
group:
  network_internal:
    control: hidden
    entities:
    - sensor.esp8266_1
    - sensor.rpi_dev
    - sensor.rpi_prod
    - sensor.winbox
    
    
homeassistant:
  customize:
    group.network_internal:
      friendly_name: 'Network - Internal'
    device_tracker.esp8266:
      hidden: true
    device_tracker.rpi_prod:
      hidden: true
    device_tracker.rpi_dev:
      hidden: true
    device_tracker.winbox:
      hidden: true