############################################################################
##  Loads the `OpenHardwareMonitor` component
############################################################################
homeassistant:
  customize_glob:
    sensor.winbox*:
      hidden: true
############################################################################
sensor:
  - platform: openhardwaremonitor
    host: 192.168.1.10
############################################################################