#######################################################################################################################################
##  RF Switches
#######################################################################################################################################
homeassistant:
  customize:
    switch.rf01:
      friendly_name: "Stua - Varmeovn"
      icon: mdi:power
    switch.rf02:
      friendly_name: "Security Cam #01"
      icon: mdi:camcorder
    switch.rf03:
      friendly_name: "Kaffe"
      icon: mdi:coffee
    switch.rf04:
      friendly_name: "Soverom - Nattbord lys"
      icon: mdi:lightbulb
    switch.rf05:
      friendly_name: "Stua - Lys i vindu"
      icon: mdi:lightbulb
    switch.rf06:
      friendly_name: "LG TV"
      icon: mdi:television
#######################################################################################################################################
switch:
  platform: rpi_rf
  gpio: 21
  switches:
    rf01:
      code_on: 14501204
      code_off: 14501201
    rf02:
      code_on: 14504276
      code_off: 14504273
    rf03:
      code_on: 14505044
      code_off: 14505041
    rf04:
      code_on: 14505236
      code_off: 14505233
    rf05:
      code_on: 16598356
      code_off: 16598353
    rf06:
      code_on: 16601428
      code_off: 16601425
#######################################################################################################################################