############################################################################
## Packages / Statistic
##
## @description Various statistics about my usage of HA
## @license     MIT
## @author      @ludeeus
############################################################################
sensor:
  - platform: template
    sensors:
      active_clients:
        unit_of_measurement: 'clients'
        value_template: "{{ states.device_tracker | selectattr('state', 'eq', 'home') | selectattr('attributes.scanner', 'eq', 'NmapDeviceScanner') | list | count}}"
      number_of_different_states_in_ha:
        value_template: "{{ states | list | count}}"