#######################################################################################################################################
##  Sunset
#######################################################################################################################################
homeassistant:
  customize:
    automation.turn_on_lights_at_sunset:
      hidden: true
#######################################################################################################################################
automation:
  alias: "Turn on lights at sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-02:00:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: "off"
  action:
    service: switch.turn_on
    entity_id: 
      - switch.rf05
      - switch.desk_lamp