#######################################################################################################################################
##  Test
#######################################################################################################################################
# Customize all entities in a domain
homeassistant:
  customize_domain:
    automation:
      hidden: true
