#######################################################################################################################################
##  Test
#######################################################################################################################################
homeassistant:
  customize_domain:
    automation:
      hidden: true
