#######################################################################################################################################
##  Test
#######################################################################################################################################
homeassistant:
  customize_domain:
    automation:
      hidden: false
      icon: mdi:home