############################################################################
##  Tracker
############################################################################
############################################################################
automation:
  - alias: 'Set "Not Home" mode'
    trigger:
      platform: state
      entity_id: device_tracker.iphone
    action:
      service_template: >
        {% if is_state("device_tracker.iphone", "home") %}
        input_boolean.turn_off
        {%- else -%}
        input_boolean.turn_on
        {%- endif %}
      entity_id: input_boolean.not_home
############################################################################
group:
  tracker:
    name: Tracker
    entities:
      - device_tracker.iphone
  equipment:
    name: Equipment
    entities:
      - device_tracker.00155d010a01
      - device_tracker.3ccd93dfb53d
      - device_tracker.70ee50061284
      - device_tracker.94103e3e8f31
      - device_tracker.b827ebee3dd8
      - device_tracker.broadlink_rmminie3bfb4
      - device_tracker.chromecastaudio
      - device_tracker.desktopvdgo64i
      - device_tracker.esp_029a1a
      - device_tracker.gwa0cc2bfd2947
      - device_tracker.hassbian
      - device_tracker.huebox
      - device_tracker.iphone
      - device_tracker.iphone_2
      - device_tracker.joakim
      - device_tracker.joakimsipad
      - device_tracker.netatmowelcome13cc96
      - device_tracker.routerasuscom
      - device_tracker.rtac66ud6b0
      - device_tracker.stuaatv
      - device_tracker.ubuntu
      - device_tracker.ubuntubox
############################################################################
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
