############################################################################
##  Tracker
############################################################################
############################################################################
automation:
  - alias: 'Set "Not Home" mode'
    trigger:
      platform: state
      entity_id: device_tracker.iphone
    action:
      service_template: >
        {% if is_state("device_tracker.iphone", "home") %}
        input_boolean.turn_off
        {%- else -%}
        input_boolean.turn_on
        {%- endif %}
      entity_id: input_boolean.not_home
############################################################################
group:
  tracker:
    name: Tracker
    entities:
      - device_tracker.iphone
############################################################################
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 10