############################################################################
##  Version Control
############################################################################
automation:
  - alias: Hass Updater
    trigger:
      - platform: state
        entity_id: sensor.pypi_ha_version
    action:
      - service: script.notify
        data_template:
          message: "Home Assistant  {{ states.sensor.pypi_ha_version.state }}  is now available."
sensor:
  - platform: command_line
    name: 'PyPi HA Version'
    command: curl -s https://api.github.com/repos/home-assistant/home-assistant/releases/latest | grep tag_name | awk -F'"' '{print $4}'